services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    container_name: akasha_postgres
    ports:
      - "9093:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: akasha
      POSTGRES_PASSWORD: "ndy0IdJXkIkfVkiFiTkBY1sFHgCTtUTe"
    volumes:
      - akasha_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    container_name: akasha_redis
    ports:
      - "9094:6379"
    command: redis-server --requirepass "MC8nBpT-wAhlFdiEZGMzmwaTnI9zFuJk"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    container_name: akasha_postgres_test
    ports:
      - "9095:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: akasha_test
      POSTGRES_PASSWORD: "1W_sL7_nHeNRCFrOT-KphY9MTYLhoYPs"
    volumes:
      - akasha_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    container_name: akasha_redis_test
    ports:
      - "9096:6379"
    command: redis-server --requirepass "_Smjod5R33eMaTohlBzli_dZ1E7LyvaW"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  akasha_data:
  akasha_test_data:
