name: akasha_client
description: The (serverpod based) client of Akasha back-end.

environment:
  sdk: "^3.8.0"

resolution: workspace

dependencies:
  serverpod_auth_idp_client: 3.4.6
  serverpod_client: 3.4.6
